name: code-formatter

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: ministryofjustice/github-actions/code-formatter@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
