name: code-formatter

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: ministryofjustice/github-actions/code-formatter@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
